trigger: none

pool:
  vmImage: ubuntu-latest
  
steps:
  - template: prepare-agent.yaml
  - task: PowerShell@2
    displayName: 'Build and test'
    inputs:
      filePath: './build.ps1'
      arguments: 'BuildAndTest'