parameters:
  - name: deploymentName
    type: string
  - name: environmentName
    type: string
  - name: serviceConnectionName
    type: string
  - name: webAppResourceName
    type: string
  - name: databaseConnectionString
    type: string
  - name: cleanFirst
    type: string
    default: false
    values:
      - true
      - false
  - name: dataSeedMode
    type: string
    default: None
    values:
      - None
      - Minimal
      - Full
      - Load

jobs:
  - deployment: ${{ parameters.deploymentName }}
    environment:
      name: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: UseDotNet@2
              inputs:
                packageType: "sdk"
                useGlobalJson: true
                workingDirectory: "$(Agent.BuildDirectory)/build-artifacts"
            - task: AzureCLI@2
              displayName: "Dotnet migrate"
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                scriptType: "pscore"
                scriptLocation: "inlineScript"
                inlineScript: "dotnet $(Agent.BuildDirectory)/build-artifacts/Migrations/Migrations.dll '${{ parameters.databaseConnectionString }}' --cleanFirst ${{ parameters.cleanFirst }} --dataSeedMode ${{ parameters.dataSeedMode }}"
            - task: AzureWebApp@1
              displayName: "Deploy Web App"
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                appType: "webAppLinux"
                appName: ${{ parameters.webAppResourceName }}
                package: "$(Agent.BuildDirectory)/build-artifacts/Web/"
                runtimeStack: "DOTNETCORE|10.0"
