//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class ApiClient {
  private http: {
    fetch(url: RequestInfo, init?: RequestInit): Promise<Response>;
  };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    baseUrl?: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> },
  ) {
    this.http = http ? http : (window as any);
    this.baseUrl = baseUrl ?? "";
  }

  /**
   * @return Success
   */
  getWeather(signal?: AbortSignal): Promise<GetWeatherResponse> {
    let url_ = this.baseUrl + "/api/weather/GetWeather";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      signal,
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetWeather(_response);
    });
  }

  protected processGetWeather(response: Response): Promise<GetWeatherResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as GetWeatherResponse);
        return result200;
      });
    } else if (status === 500) {
      return response.text().then((_responseText) => {
        let result500: any = null;
        result500 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Server Error",
          status,
          _responseText,
          _headers,
          result500,
        );
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<GetWeatherResponse>(null as any);
  }

  /**
   * @return Success
   */
  createUser(
    request: CreateUserRequest,
    signal?: AbortSignal,
  ): Promise<CreateUserResponse> {
    let url_ = this.baseUrl + "/api/user/CreateUser";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(request);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      signal,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processCreateUser(_response);
    });
  }

  protected processCreateUser(response: Response): Promise<CreateUserResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as CreateUserResponse);
        return result200;
      });
    } else if (status === 400) {
      return response.text().then((_responseText) => {
        let result400: any = null;
        result400 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Bad Request",
          status,
          _responseText,
          _headers,
          result400,
        );
      });
    } else if (status === 500) {
      return response.text().then((_responseText) => {
        let result500: any = null;
        result500 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Server Error",
          status,
          _responseText,
          _headers,
          result500,
        );
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<CreateUserResponse>(null as any);
  }

  /**
   * @return Success
   */
  getUsers(signal?: AbortSignal): Promise<GetUsersResponse> {
    let url_ = this.baseUrl + "/api/user/GetUsers";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      signal,
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetUsers(_response);
    });
  }

  protected processGetUsers(response: Response): Promise<GetUsersResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as GetUsersResponse);
        return result200;
      });
    } else if (status === 500) {
      return response.text().then((_responseText) => {
        let result500: any = null;
        result500 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Server Error",
          status,
          _responseText,
          _headers,
          result500,
        );
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<GetUsersResponse>(null as any);
  }

  /**
   * @return Success
   */
  getSecretMessage(
    password: string,
    signal?: AbortSignal,
  ): Promise<GetSecretMessageResponse> {
    let url_ = this.baseUrl + "/api/secret/GetSecretMessage?";
    if (password === undefined || password === null)
      throw new globalThis.Error(
        "The parameter 'password' must be defined and cannot be null.",
      );
    else url_ += "password=" + encodeURIComponent("" + password) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      signal,
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetSecretMessage(_response);
    });
  }

  protected processGetSecretMessage(
    response: Response,
  ): Promise<GetSecretMessageResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as GetSecretMessageResponse);
        return result200;
      });
    } else if (status === 500) {
      return response.text().then((_responseText) => {
        let result500: any = null;
        result500 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Server Error",
          status,
          _responseText,
          _headers,
          result500,
        );
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<GetSecretMessageResponse>(null as any);
  }

  /**
   * @return Success
   */
  createActivity(
    request: CreateActivityRequest,
    signal?: AbortSignal,
  ): Promise<CreateActivityResponse> {
    let url_ = this.baseUrl + "/api/activity/CreateActivity";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(request);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      signal,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processCreateActivity(_response);
    });
  }

  protected processCreateActivity(
    response: Response,
  ): Promise<CreateActivityResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as CreateActivityResponse);
        return result200;
      });
    } else if (status === 400) {
      return response.text().then((_responseText) => {
        let result400: any = null;
        result400 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Bad Request",
          status,
          _responseText,
          _headers,
          result400,
        );
      });
    } else if (status === 500) {
      return response.text().then((_responseText) => {
        let result500: any = null;
        result500 =
          _responseText === ""
            ? null
            : (JSON.parse(
                _responseText,
                this.jsonParseReviver,
              ) as ApiErrorResponse);
        return throwException(
          "Server Error",
          status,
          _responseText,
          _headers,
          result500,
        );
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<CreateActivityResponse>(null as any);
  }
}

export interface ApiErrorResponse {
  message?: string | undefined;
  stackTrace?: string | undefined;
  userVisibleMessage?: string | undefined;
}

export interface GetWeatherResponse {
  temperature: number;
  windSpeed: number;
  description: string;
}

export interface CreateUserResponse {
  id: number;
  name: string;
  email: string;
}

export interface CreateUserRequest {
  name: string;
  email: string;
}

export interface GetUsersResponse {
  users: GetUsersResponseUserResponse[];
}

export interface GetUsersResponseUserResponse {
  id: number;
  name: string;
  email: string;
}

export interface GetSecretMessageResponse {
  message: string;
}

export interface GetSecretMessageRequest {}

export interface CreateActivityResponse {
  id: number;
}

export interface CreateActivityRequest {
  activity: ActivityDto;
}

export interface ActivityDto {
  name: string;
  userId: string;
  title: string;
  distanceInMeters: number;
  dateOfActivity: string;
  imageUri?: string | undefined;
  commentIndices?: number[] | undefined;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  throw new ApiException(message, status, response, headers, result);
}
